//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr.assets.pages {
	
	
	public partial class SignUp {
		
		protected System.Web.UI.HtmlControls.HtmlInputText name;
		
		protected System.Web.UI.HtmlControls.HtmlInputText last_name;
		
		protected System.Web.UI.HtmlControls.HtmlInputText username;
		
		protected System.Web.UI.HtmlControls.HtmlInputText phone;
		
		protected System.Web.UI.HtmlControls.HtmlInputText email;
		
		protected System.Web.UI.HtmlControls.HtmlInputText password;
		
		protected System.Web.UI.HtmlControls.HtmlInputText password_repeat;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor send;
	}
}
