//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr.assets.pages {
	
	
	public partial class SignIn {
		
		protected System.Web.UI.HtmlControls.HtmlInputText email;
		
		protected System.Web.UI.HtmlControls.HtmlInputText password;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor enter;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl errorBox;
	}
}
