//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr.assets.pages.admin {
	
	
	public partial class AddItem {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager sm;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor addButton;
		
		protected System.Web.UI.HtmlControls.HtmlInputText title;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea description;
		
		protected System.Web.UI.HtmlControls.HtmlInputText price;
		
		protected System.Web.UI.HtmlControls.HtmlInputText photos;
	}
}
